language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lordprat/docker-react -f Dockerfile.dev .

script:
    - docker run lordprat/docker-react npm run test -- --coverage